# default
spring:
    profiles:
        active: local

---
# local 환경
spring:
    config:
        activate:
            on-profile: local
    jpa:
        defer-datasource-initialization: true # hibernate가 초기화되기 전 data.sql 실행하는 것을 방지
        show-sql: true
        hibernate:
            ddl-auto: create-drop

    datasource:
        url: jdbc:h2:mem:testdb # db 주소 고정
        data: classpath:data-for-h2.sql # 시작할때 실행시킬 script
    devtools:
        livereload:
            enabled: true